---

language: node_js
node_js:
  - node
env:
  global:
    CC_TEST_REPORTER_ID=b1be8d44cbfd1a360a2b50ed4c1f2cd9d761e2f07c86582ad928592159e7452b
install:
  npm install -g browserify
before_script:
  make asm
script:
  - make test